### ISSUE TITLE
Association analysis between given cell categories

### ISSUE THREAD

**Issue by Yijun-Tian** [immunogenomics/presto#15]
Hello,
Just a sudden idea about association or linear regression analysis between cells with given categorical annotations in presto. Would that be difficult to implement such a feature?
Thank you for this great work!

**Comment by kaizen89** [comment]
Hi @slowkow, is `limm` also applicable to single cell data.

**Comment by slowkow** [comment]
@kaizen89

Please consider:

1. Posting questions to [Biostars](https://www.biostars.org/), where experts can answer your questions and help you find more resources.

2. Searching PubMed to find examples of single-cell analyses that have been published. Some papers have descriptions in the Methods section that can be useful. Some papers also provide accompanying source code that you can read and learn from.

3. Setting up a 1-to-1 meeting with a local bioinformatics expert in your institution. If you already have a dataset in-hand, you might consider sharing some details about it and asking questions about what statistical methodology they might recommend.

I hope you understand that we'd like to limit the scope of the presto GitHub issues page for discussion of issues with the presto package. Discussion of other topics is out of scope here. Thanks for your understanding!
