### ISSUE TITLE
find genes with expression in cluster A higher by a given FC than any other cluster 

### ISSUE THREAD

**Issue by kaizen89** [immunogenomics/presto#17]
Hi, 
Thanks for this nice package.
I was wandering if it was possible to add a feature to find genes with an expression in cluster A , let's say 2 times higher than any other cluster among B,C and D, instead of grouping all the cells outside of cluster A which could dilute the expression of the genes.
Thanks!

**Comment by slowkow** [comment]
@kaizen89

We can re-reun `presto::wilcoxauc(mat, group)` as many times as we wish with any variables we define. We can decide for ourselves how to define `mat` (e.g. what cells to include or not). We can also define `group` however we wish (e.g. `1` when cluster A and `2` when cluster B, C, or D).

**Comment by kaizen89** [comment]
Thanks for your answer @slowkow.
So if I have 10 clusters that would make 55 different comparisons, I was hoping to use another approach.^^
I will try to figure out a solution that would not require to run all the combinations.
