### ISSUE TITLE
is there an easier way to get the pct.out for each of the outside clusters 

### ISSUE THREAD

**Issue by crazyhottommy** [immunogenomics/presto#2]
I can hack to have a function myself, but would be nice to have it output from presto.

Thanks!

**Comment by slowkow** [comment]
This information is already given in the column called `pct_in`.

For example, let's look at one of the listings in the [vignette][1]:

[1]: http://htmlpreview.github.io/?https://github.com/immunogenomics/presto/blob/master/docs/getting-started.html

```
head(wilcoxauc(exprs, y))
##   feature group avgExpr  logFC statistic  auc    pval    padj pct_in pct_out
## 1      G1     A    1.15  0.082      2890 0.55 2.6e-01 6.4e-01     75      59
## 2      G1     B    0.36 -1.054       968 0.20 1.9e-09 4.7e-08     29      80
## 3      G1     C    1.70  0.910      3618 0.72 2.9e-06 2.4e-05     86      54
## 4     G10     A    1.00  0.147      2976 0.57 1.3e-01 4.7e-01     69      51
## 5     G10     B    1.24  0.483      2838 0.60 3.8e-02 7.8e-02     64      54
## 6     G10     C    0.50 -0.610      1661 0.33 3.7e-04 1.1e-03     38      67
```

By looking at column `pct_in`, we can see that:
- 75% of cells in group A express G1
- 29% of cells in group B express G1
- 86% of cells in group C express G1

By looking at column `pct_out`, we can see that:
- 59% of cells outside of group A express G1 (this includes all cells in groups B and C)

**Comment by crazyhottommy** [comment]
ah, sorry about that... I do not know what I was thinking about.. Thanks a lot!
