### ISSUE TITLE
install fails R 4.2.2

### ISSUE THREAD

**Issue by niko-balanis** [immunogenomics/presto#22]
I get this issue on the newest R

install.packages("presto")

Warning in install.packages :
  package ‘presto’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by niko-balanis** [comment]
It works with devtools install. maybe that should be the listed method on the github

**Comment by wish1832** [comment]
+1 on this one. I'm using R 4.2.2 and I get the same message, but `devtools::install_github("immunogenomics/presto")` worked.

**Comment by ajynair** [comment]
Even devtools install shows error for me.
> devtools::install_github("immunogenomics/presto")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 53/60
  Rate limit reset at: 2023-04-30 21:15:46 UTC

**Comment by slowkow** [comment]
@ajynair I just ran `devtools::install_github("immunogenomics/presto")` successfully on R version 4.2.3 (2023-03-15).

Please consider sharing your `sessionInfo()`.

**Comment by schwebels** [comment]
I am getting the same error when running   devtools::install_github("immunogenomics/presto")
R version 4.3.3 (2024-02-29 ucrt) 

package ‘devtools’ successfully unpacked and MD5 sums checked

> devtools::install_github("immunogenomics/presto")
Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 57/60
  Rate limit reset at: 2024-04-29 21:01:47 UTC


SessionInfo()
R version 4.3.3 (2024-02-29 ucrt) 
Platform: x86_64-w64-mingw32/x64 (64-bit) 
Running under: Windows 11 x64 (build 22631)  
Matrix products: default   
locale: 
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United States.utf8      
time zone: America/New_York
tzcode source: internal 
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base       
loaded via a namespace (and not attached):  [1] vctrs_0.6.5         cli_3.6.2           rlang_1.1.3         stringi_1.8.3       purrr_1.0.2         pkgload_1.3.4       promises_1.3.0      shiny_1.8.1.1        [9] xtable_1.8-4        glue_1.7.0          htmltools_0.5.8.1   httpuv_1.6.15       pkgbuild_1.4.4      ellipsis_0.3.2      fastmap_1.1.1       lifecycle_1.0.4     [17] memoise_2.0.1       BiocManager_1.30.22 stringr_1.5.1       compiler_4.3.3      miniUI_0.1.1.1      sessioninfo_1.2.2   fs_1.6.3            htmlwidgets_1.6.4   [25] Rcpp_1.0.12         urlchecker_1.0.1    rstudioapi_0.16.0   later_1.3.2         digest_0.6.35       R6_2.5.1            curl_5.2.1          usethis_2.2.3       [33] magrittr_2.0.3      tools_4.3.3         mime_0.12           devtools_2.4.5      profvis_0.3.8       remotes_2.5.0       cachem_1.0.8

Thanks for your help!

**Comment by slowkow** [comment]
@schwebels I just tried searching the web for this query:

```
Error: Failed to install 'unknown package' from GitHub: HTTP error 401. Bad credentials
```

and I found a few relevant links:

- https://stackoverflow.com/questions/70908295/failed-to-install-unknown-package-from-github
- https://forum.posit.co/t/unable-to-install-packages-from-github/124372

I'm copying the suggestion from the Posit forums here:

> This arises from an obscure feature in devtools. Check to see if you have a personal access token (PAT) set with
> 
> `Sys.getenv("GITHUB_PAT")`
>
> If you do, make a careful record of it, then remove from the environment with
> 
> `Sys.unsetenv("GITHUB_PAT")`

Good luck! Let us know if you still have issues after removing your PAT.

**Comment by schwebels** [comment]
thanks for your help!
